name: arkit_plugin_example
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

  arkit_plugin: ^1.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/
